### ISSUE TITLE
Update conda-forge packages

### ISSUE THREAD

**Issue by sbliven** [CZ-NIC/pyoidc#842]
I'm not sure who's responsible for this, but it would be lovely if the conda-force oic package could get updated. Right now the most recent version is 0.15.1 with support for python 3.4-3.7. Of course pip is still an option, but I always prefer the native conda recipe if possible.

**Comment by schlenk** [comment]
Might be better aimed at the conda-forge repo? It has instructions how to get a new version published.

https://github.com/conda-forge/oic-feedstock
