### ISSUE TITLE
Update URL references after repo move

### ISSUE THREAD

**Issue by tpazderka** [CZ-NIC/pyoidc#845]
Repo has been moved, update URL references.

**Comment by infohash** [comment]
What is the reason of moving the repo? Will we get more maintainers? Also, @rohe has been working on [IdentityPython/JWTConnect-Python-OidcRP (3rd layer in the JWTConnect stack: cryptojwt, oidcmsg, oidcrp)](https://github.com/IdentityPython/JWTConnect-Python-OidcRP) and [IdentityPython/idpy-oidc (2nd layer in the JwtConnect stack: cryptojwt, idpyoidc)[https://github.com/IdentityPython/idpy-oidc). I think I can port their features into pyoidc.

**Comment by tpazderka** [comment]
@rohe and I have been asked to free up the previous organization name and we had no reason not to do that.

More maintainers can happen in the near future.

As for PR with improvements and features, they are always welcome.
