### ISSUE TITLE
Release 1.5.1

### ISSUE THREAD

**Issue by gbip** [CZ-NIC/pyoidc#858]
Would it be possible to release version `1.5.1` which would include the changes made to support OIDC session ID ?

Thanks !

**Comment by tpazderka** [comment]
There are a few changes in the codebase that would warrant a new release (but it would have to be `1.6.0`). I will wait for @schlenk to finish up the pending PR and I will prepare the release.

**Comment by tpazderka** [comment]
Released as `1.6.0`, sorry it took that long :(

**Comment by gbip** [comment]
> 1.6.0

Thank you !!

**Comment by schlenk** [comment]
I just updated the listing at https://github.com/CZ-NIC/pyoidc/releases too.
