### ISSUE TITLE
Now in seconds vs. milliseconds: IATError: Issued in the future

### ISSUE THREAD

**Issue by chrislondon** [CZ-NIC/pyoidc#864]
I'm trying to implement World Coin SSO but it appears that their OIDC returns an IAT in milliseconds but OIC compares it with "now" in seconds.

```python
# oic/message.py line 799
if _now < (_iat - _skew):
    # _now = 1690410254
    # _iat = 1690410253829
    raise IATError("Issued in the future")
```

I'm not seeing any option in the code to change either the iat or now to use seconds/milliseconds.

**Comment by schlenk** [comment]
If they send IAT claims that are milliseconds they directly violate RFC 7519.  (https://www.rfc-editor.org/rfc/rfc7519.html#page-10 )

> [4.1.6](https://www.rfc-editor.org/rfc/rfc7519.html#section-4.1.6).  "iat" (Issued At) Claim

> The "iat" (issued at) claim identifies the time at which the JWT was
    issued.  This claim can be used to determine the age of the JWT.  Its
    value MUST be a number containing a NumericDate value.  Use of this
    claim is OPTIONAL.

> NumericDate
      A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
      2013 Edition [[POSIX.1](https://www.rfc-editor.org/rfc/rfc7519.html#ref-POSIX.1)] definition "Seconds Since the Epoch", in
      which each day is accounted for by exactly 86400 seconds, other
      than that non-integer values can be represented.  See [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339)
      [[RFC3339](https://www.rfc-editor.org/rfc/rfc3339)] for details regarding date/times in general and UTC in
      particular.

You could probably pass in a huge negative "skew" kwarg into the verify method to compensate for this failure of World Coins implementation. Or override the IDToken class and add your own method to allow milliseconds.

**Comment by chrislondon** [comment]
Thanks for the info!
